<a href="https://colab.research.google.com/github/MariuszGrecki/Machine_learning_tutorial/blob/main/regression/O2_gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Regresja liniowa - spadek wzdłuż gradientu**

Zawsze poszukujemy minimum, na poczatku losowo dobieramy parametry:
- punkt startowy
-

dane->obliczanie straty->aktualizacja parametrów ponownie drugi krok

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

np.random.seed(42)

In [2]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y =np.array([3000,3250,3500,3750,4000,4250])
m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [3]:
X1 = X1.reshape(m, 1)
Y = Y.reshape(-1, 1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [4]:
bias = np.ones((m, 1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [5]:
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


Losowa Inicjalizacja parametrów

In [6]:
#wskaźnik uczenia
eta = 0.01


weights = np.random.randn(2, 1)
print(X)
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[ 0.49671415]
 [-0.1382643 ]]


In [10]:
#Metoda gradientu prostego
intercept = []
coef = []

for i in range(3000):
  gradient = (2 / m) * X.T.dot(X.dot(weights) - Y)
  weights = weights - eta * gradient
  intercept.append(weights[0][0])
  coef.append(weights[1][0])

print(weights)

[[2749.99999924]
 [ 250.00000018]]


In [11]:
df = pd.DataFrame(data={'intercept' : intercept, 'coef': coef})
df.head()

intercept        coef
0  2749.956169  250.010238
1  2749.956329  250.010201
2  2749.956489  250.010163
3  2749.956648  250.010126
4  2749.956806  250.010089

In [12]:
px.line(df, y='intercept', width=800, title='Dopasowanie:intercept')

In [13]:
px.line(df, y='coef', width=800, title='Dopasowanie:coef')